WC_COUNTRIES = (
    ("GROUP", "Group A"),
    ("Brazil", "BRA"),
    ("Croatia", "CRO"),
    ("Mexico", "MEX"),
    ("Cameroon", "CMR"),
    ("ENDGROUP", "Group A"),
    ("GROUP", "Group B"),
    ("Spain", "ESP"),
    ("Netherlands", "NED"),
    ("Chile", "CHI"),
    ("Australia", "AUS"),
    ("ENDGROUP", "Group B"),
    ("GROUP", "Group C"),
    ("Colombia", "COL"),
    ("Greece", "GRE"),
    ("Ivory Coast", "CIV"),
    ("Japan", "JPN"),
    ("ENDGROUP", "Group C"),
    ("GROUP", "Group D"),
    ("Uruguay", "URU"),
    ("Costa Rica", "CRC"),
    ("England", "ENG"),
    ("Italy", "ITA"),
    ("ENDGROUP", "Group D"),
    ("GROUP", "Group E"),
    ("Switzerland", "SUI"),
    ("Ecuador", "ECU"),
    ("France", "FRA"),
    ("Honduras", "HON"),
    ("ENDGROUP", "Group E"),
    ("GROUP", "Group F"),
    ("Argentina", "ARG"),
    ("Bosnia and Herzegovina", "BIH"),
    ("Iran", "IRN"),
    ("Nigeria", "NGA"),
    ("ENDGROUP", "Group F"),
    ("GROUP", "Group G"),
    ("Germany", "GER"),
    ("Portugal", "POR"),
    ("Ghana", "GHA"),
    ("United States of America", "USA"),
    ("ENDGROUP", "Group G"),
    ("GROUP", "Group H"),
    ("Belgium", "BEL"),
    ("Algeria", "ALG"),
    ("Russia", "RUS"),
    ("South Korea", "KOR"),
    ("ENDGROUP", "Group H")
)