WC_COUNTRIES = (
    ("GROUP", "Group A"),
    ("Brazil", "BRA"),
    ("Croatia", "CRO"),
    ("Mexico", "MEX"),
    ("Cameroon", "CMR"),
    ("ENDGROUP", "Group A"),
    ("GROUP", "Group B"),
    ("Spain", "ESP"),
    ("Netherlands", "NED"),
    ("Chile", "CHI"),
    ("Australia", "AUS"),
    ("ENDGROUP", "Group B"),
    ("GROUP", "Group C"),
    ("Colombia", "COL"),
    ("Greece", "GRE"),
    ("Ivory Coast", "CIV"),
    ("Japan", "JPN"),
    ("ENDGROUP", "Group C"),
    ("GROUP", "Group D"),
    ("Uruguay", "URU"),
    ("Costa Rica", "CRC"),
    ("England", "ENG"),
    ("Italy", "ITA"),
    ("ENDGROUP", "Group D"),
    ("GROUP", "Group E"),
    ("Switzerland", "SUI"),
    ("Ecuador", "ECU"),
    ("France", "FRA"),
    ("Honduras", "HON"),
    ("ENDGROUP", "Group E"),
    ("GROUP", "Group F"),
    ("Argentina", "ARG"),
    ("Bosnia and Herzegovina", "BIH"),
    ("Iran", "IRN"),
    ("Nigeria", "NGA"),
    ("ENDGROUP", "Group F"),
    ("GROUP", "Group G"),
    ("Germany", "GER"),
    ("Portugal", "POR"),
    ("Ghana", "GHA"),
    ("United States of America", "USA"),
    ("ENDGROUP", "Group G"),
    ("GROUP", "Group H"),
    ("Belgium", "BEL"),
    ("Algeria", "ALG"),
    ("Russia", "RUS"),
    ("South Korea", "KOR"),
    ("ENDGROUP", "Group H")
)

TEAM_RANKINGS = {
    "BRAZIL": 1,
    "ARGENTINA": 2,
    "GERMANY": 3,
    "SPAIN": 4,
    "BELGIUM": 5,
    "FRANCE": 6,
    "PORTUGAL": 7,
    "NETHERLANDS": 8,
    "ITALY": 9,
    "COLOMBIA": 10,
    "ENGLAND": 11,
    "URUGUAY": 12,
    "CHILE": 13,
    "RUSSIA": 14,
    "SWITZERLAND": 15,
    "MEXICO": 16,
    "CROATIA": 17,
    "ECUADOR": 18,
    "IVORY COAST": 19,
    "JAPAN": 20,
    "BOSNIA AND HERZEGOVINA": 21,
    "GHANA": 22,
    "NIGERIA": 23,
    "UNITED STATES OF AMERICA": 24,
    "GREECE": 25,
    "SOUTH KOREA": 26,
    "CAMEROON": 27,
    "AUSTRALIA": 28,
    "ALGERIA": 29,
    "IRAN": 30,
    "HONDURAS": 31,
    "COSTA RICA": 32
}